name: CI-prod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
         node-version: 14
     - run: "yarn install --frozen-lockfile"
     - run: "yarn test:unit"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /home/leo/sites/flirtesansepines
          remote_host: ${{ secrets.PROD_SFTP_HOST }}
          remote_port: ${{ secrets.PROD_SFTP_PORT }}
          remote_user: ${{ secrets.PROD_SFTP_USERNAME }}
          remote_key: ${{ secrets.PROD_SFTP_PRIVATE_KEY }}
